spring:
#MySql 连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/yu_blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456  # ← 改成你的密码
    driver-class-name: com.mysql.cj.jdbc.Driver
#Spring Security 配置
  security:
    user:
      name: admin
      password: 123456
      roles: user

  profiles:
    active: dev

# 可选：MyBatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true